#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Starting fastapi app with debugpy support..."

echo DEBUG_PORT: ${DEBUG_PORT}
# echo API_APP: ${API_APP}
# echo PORT: ${PORT}
echo ${DEBUG_HOST}
echo ${DEBUG_PORT}

# watchmedo auto-restart --recursive -p '*.py' \
#     -- python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} \
#     -m uvicorn ${API_APP} \
#         --host ${CONTROLLER_HOST} \
#         --port ${CONTROLLER_PORT} \
#         --workers 1


if [[ "${DEBUG_ENABLED}" == "true" ]]; then
    echo "Launching pydebug at port ${DEBUG_PORT}."

    watchmedo auto-restart --recursive -p '*.py' \
    -- python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} \
    -m uvicorn ${API_APP} \
        --host ${CONTROLLER_HOST} \
        --port ${CONTROLLER_PORT} \
        --workers ${UVICORN_WORKERS}
else
    echo "pydebug disabled."
    uvicorn ${API_APP} \
        --host ${CONTROLLER_HOST} \
        --port ${CONTROLLER_PORT} \
        --workers ${UVICORN_WORKERS}

fi




# watchmedo auto-restart --recursive -p '*.py' \
#     -- python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} \
#     -m api

# python -m debugpy \
#     --listen 0.0.0.0:${DEBUG_PORT} \
#     -m uvicorn api:app \
#         --host 0.0.0.0 \
#         --port 9000 --workers 1


echo "FastAPI app running! Debugpy now accepting remote attach from clients..."
